winget install Microsoft.WindowsTerminal
winget install LGUG2Z.komorebi
winget install eloston.ungoogled-chromium
winget install Microsoft.VisualStudio.2022.Community
winget install voidtools.Everything
winget install WinDirStat.WinDirStat
winget install Git.Git
winget install Microsoft.PowerToys
winget install MSYS2.MSYS2
:: Apple Music
winget install 9PFHDD62MXS1
winget install AutoHotkey.AutoHotkey
