winget install glzr-io.glazewm
winget install glzr-io.zebar
winget install eloston.ungoogled-chromium
winget install Discord.Discord
winget install Valve.Steam
winget install Microsoft.VisualStudio.2022.Community
winget install MultiMC.MultiMC
winget install voidtools.Everything
winget install WinDirStat.WinDirStat
winget install Git.Git
winget install Microsoft.PowerToys
winget install Cygwin.Cygwin
:: Apple Music
winget install 9PFHDD62MXS1
winget install OBSProject.OBSStudio
winget install AutoHotkey.AutoHotkey
winget install Nvidia.GeForceExperience
